In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from scipy.stats import linregress
import os
import csv
import datetime
import scipy.stats as sts
from pandas import Series, DataFrame

In [3]:
file = ('winedata.csv')

In [4]:
wine_df = pd.read_csv(file,  encoding="ISO-8859-2")
wine_df.head()

,index,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,First numerical,year
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",VulkĂ Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin OâKeefe,@kerinokeefe,Nicosia 2013 VulkĂ Bianco (Etna),White Blend,Nicosia,9,2013
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,21,2011
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwineÂ,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,11,2013
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,12,2013
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwineÂ,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,14,2012

In [18]:

wine_df.dtypes

index                      int64
country                   object
description               object
designation               object
points                     int64
price                    float64
province                  object
region_1                  object
region_2                  object
taster_name               object
taster_twitter_handle     object
title                     object
variety                   object
winery                    object
First numerical            int64
year                      object
dtype: object

In [22]:
wine_ratings_df = pd.DataFrame(wine_df)
wine_ratings_df.head()

,index,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,First numerical,year
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",VulkĂ Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin OâKeefe,@kerinokeefe,Nicosia 2013 VulkĂ Bianco (Etna),White Blend,Nicosia,9,2013
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,21,2011
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwineÂ,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,11,2013
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,12,2013
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwineÂ,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,14,2012

0         Sicily & Sardinia
1                     Douro
2                    Oregon
3                  Michigan
4                    Oregon
                ...
129966                Mosel
129967               Oregon
129968               Alsace
129969               Alsace
129970               Alsace
Name: province, Length: 129971, dtype: object

In [34]:
#winegb_df= wine_ratings_df.groupby(['province'])
#winegb_df

In [43]:
wine_avg_score=wine_ratings_df.groupby(['points']).mean()
wine_score_clean=wine_avg_score.sort_index(ascending=False)

wine_pricetoscore_df = pd.DataFrame(wine_score_clean['price'])
wine_pricetoscore_df

             price
points
100     485.947368
99      284.214286
98      245.492754
97      207.173913
96      159.292531
95      109.235420
94       81.436938
93       63.112216
92       51.037763
91       43.224252
90       36.906622
89       32.169640
88       28.687523
87       24.901884
86       22.133759
85       19.949562
84       19.310215
83       18.237353
82       18.870767
81       17.182353
80       16.372152

In [78]:
ranked_df=wine_ratings_df.groupby(['winery']).mean()
ranked_df1=pd.DataFrame(ranked_df)
results=ranked_df1.sort_values(['points'], ascending=False)
best_winery_df=results.drop('First numerical', 1)
best_winery_df

                       index  points  price
winery
Araujo               41837.0    98.0  275.0
Gandona             121889.0    97.0  190.0
J.L. Chave          100002.0    97.0  125.0
Ovid                121887.0    97.0  195.0
Salon                48035.6    96.8  380.6
...                      ...     ...    ...
Rojo Mojo           121880.0    80.0    9.0
Hawthorne Ridge      90904.0    80.0    8.0
T                   116139.0    80.0   11.0
NamastĂŠ Vineyards   14341.0    80.0   15.0
ChĂ˘teau Majoureau   90927.0    80.0   25.0

[16757 rows x 3 columns]

In [97]:
#wine_ratings_df.head()

winery_region_df=wine_ratings_df[['winery','country','province',]]
winery_region_df['country'].value_counts()

US                        54504
France                    22093
Italy                     19540
Spain                      6645
Portugal                   5691
Chile                      4472
Argentina                  3800
Austria                    3345
Australia                  2329
Germany                    2165
New Zealand                1419
South Africa               1401
Israel                      505
Greece                      466
Canada                      257
Hungary                     146
Bulgaria                    141
Romania                     120
Uruguay                     109
Turkey                       90
Slovenia                     87
Georgia                      86
England                      74
Croatia                      73
Mexico                       70
Moldova                      59
Brazil                       52
Lebanon                      35
Morocco                      28
Peru                         16
Ukraine                      14
Serbia                       12
Czech Republic               12
Macedonia                    12
Cyprus                       11
India                         9
Switzerland                   7
Luxembourg                    6
Armenia                       2
Bosnia and Herzegovina        2
Egypt                         1
China                         1
Slovakia                      1
Name: country, dtype: int64

In [104]:
region_count_df=winery_region_df['province'].value_counts().head(10)
region_count_df

California          36247
Washington           8639
Bordeaux             5941
Tuscany              5897
Oregon               5373
Burgundy             3980
Northern Spain       3851
Piedmont             3729
Mendoza Province     3264
Veneto               2716
Name: province, dtype: int64